apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: utq3hscd8-go 
  janus-idp.io/tekton: utq3hscd8-go
  backstage.io/kubernetes-id: utq3hscd8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: utq3hscd8-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml