apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: utq3hscd8-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: utq3hscd8-go 
  name: utq3hscd8-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: utq3hscd8-go 
